source 'http://rubygems.org'

gem 'nokogiri', '1.8.5'
gem 'jekyll-sitemap'
gem 'jekyll-seo-tag'
gem 'jekyll-gist'
gem 'jekyll-feed'
gem 'jemoji'
gem 'rake'
gem 'github-pages'
gem 'html-proofer'
gem 'jekyll-email-protect'
gem 'rouge'