[build]
command = "npm run build"
ignore = "git log -1 --pretty=%B | grep depfu"
publish = "dist"

[context.production]
environment = {ELEVENTY_ENV = "production"}

[context.deploy-preview]
environment = {ELEVENTY_ENV = "preview"}

[context.branch-deploy]
environment = {ELEVENTY_ENV = "branch"}

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = 'null'
# TODO
Content-Security-Policy = ""
Referrer-Policy = "no-referrer-when-downgrade"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-UA-Compatible = "IE=edge,chrome=1"
X-XSS-Protection = "1; mode=block"

[[plugins]]
package = "netlify-plugin-submit-sitemap"

[plugins.inputs]
baseUrl = "https://sylvain.dev"
providers = ["google", "bing"]
sitemapPath = "/sitemap.xml"

[[plugins]]
package = "netlify-plugin-no-more-404"

[plugins.inputs]
cacheKey = "theme-skip2"
debugMode = false
on404 = "warn"

[[plugins]]
package = "netlify-plugin-checklinks"

[plugins.inputs]
entryPoints = [
  "*.html",
]
recursive = true
pretty = true
skipPatterns = []
todoPatterns = []
checkExternal = false
followSourceMaps = false
