[build]
ignore = "git log -1 --pretty=%B | grep depfu"
command = "npm run production"
publish = "dist"

[context.production]
environment = { ELEVENTY_ENV = "production" }

[context.deploy-preview]
environment = { ELEVENTY_ENV = "preview" }

[context.branch-deploy]
environment = { ELEVENTY_ENV = "branch" }

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Content-Security-Policy = "default-src 'self'; connect-src 'self'; font-src 'self'; img-src 'self' data: https://www.netlify.com; script-src 'self'; style-src 'unsafe-inline'; worker-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; media-src 'self'; object-src: 'none'"
X-UA-Compatible = "IE=edge,chrome=1"
Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
X-XSS-Protection = "1; mode=block"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[[headers]]
for = "/admin/*"

[headers.values]
Content-Security-Policy = "default-src 'self'; connect-src 'self'; font-src 'self'; img-src 'self' data: https://www.netlify.com; script-src 'unsafe-eval' 'unsafe-inline' 'self' identity.netlify.com unpkg.com; style-src 'unsafe-inline'; worker-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; media-src 'self'; object-src: 'none'"

[[plugins]]
package = "netlify-plugin-submit-sitemap"

[plugins.inputs]
baseUrl = "https://sylvain.dev"
sitemapPath = "/sitemap.xml"
providers = ["google", "bing"]
