[build]
  base = "./"
  publish = "_site/"
  command = "eleventy"
  environment = { IS_NETLIFY="true" }

[context.deploy-preview]
  publish = "_site/"
  environment = { DEBUG = "*", IS_NETLIFY="true" }
