[build]
  command = "npm run production"
  publish = "dist"

[context.deploy-preview]
  environment = { DEBUG = "*", ELEVENTY_ENV="preview" }

[context.branch-deploy]
  environment = { DEBUG = "*", ELEVENTY_ENV="branch" }
