[build]
command = "npm run production"
publish = "dist"

[context.production]
environment = { ELEVENTY_ENV = "production" }

[context.deploy-preview]
environment = { ELEVENTY_ENV = "preview" }

[context.branch-deploy]
environment = { ELEVENTY_ENV = "branch" }

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
