// From https://github.com/nhoizey/nicolas-hoizey.com

// CSS is included a data file so it can be compiled and inlined at runtime
// Individual files are also generated by `/site/css.njk`

const { compileSassTargets } = require("../_functions/scss");

const targets = {
  main: "/_sass/style.scss"
};

// Create an object with the compiled CSS for each key in targets
module.exports = compileSassTargets(targets);
