module.exports = [
  { name: "twitter", url: "https://twitter.com/" },
  { name: "github", url: "https://github.com/" },
  { name: "facebook", url: "https://facebook.com/" },
  { name: "google", url: "https://twitter.com/" },
  { name: "instagram", url: "https://twitter.com/" },
  { name: "pinterest", url: "https://twitter.com/" },
  { name: "linkedin", url: "https://www.linkedin.com/in/" },
  { name: "youtube", url: "https://twitter.com/" },
  { name: "spotify", url: "https://open.spotify.com/user/" },
  { name: "github", url: "https://github.com/" },
  { name: "gitlab", url: "https://gitlab.com/" },
  { name: "lastfm", url: "https://twitter.com/" },
  { name: "stackoverflow", url: "https://stackoverflow.com/users/" },
  { name: "quora", url: "https://twitter.com/" },
  { name: "reddit", url: "https://twitter.com/" },
  { name: "medium", url: "https://medium.com" },
  { name: "vimeo", url: "https://twitter.com/" },
  { name: "lanyrd", url: "https://twitter.com/" },
  { name: "devto", url: "https://dev.to/" },
  { name: "email", url: "mailto:" },
];
