--- 
backend: 
  branch: develop
  name: github
  repo: sylvainmetayer/sylvainmetayer
collections: 
  - 
    create: true
    fields: 
      - 
        label: Titre
        name: title
        widget: string
      - 
        label: Description
        name: description
        widget: string
      - 
        default: sylvainmetayer
        label: Auteur
        name: author
        widget: string
      - 
        default: post
        label: Layout
        name: layout
        widget: string
      - 
        label: Texte
        name: body
        widget: markdown
      - 
        label: Catégorie
        name: category
        options: 
          - blog
          - projet
        widget: select
      - 
        label: "Type de projet (si catégorie = projet)"
        name: project_type
        options: 
          - school
          - personal
        required: false
        widget: select
      - 
        label: Tags
        max: 3
        min: 0
        name: tag
        widget: string
      - 
        default: false
        label: "Star the article"
        name: star
        widget: boolean
      - 
        default: false
        label: "Activate comments on this page"
        name: enable_comments
        widget: boolean
    folder: _posts
    label: Posts
    name: Posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  - 
    files: 
      - 
        fields: 
          - 
            label: Nom
            name: name
            widget: string
          - 
            label: URL
            name: link
            widget: string
        file: src/_data/certifications.yml
        label: Certifications
        name: certifications
    label: Configuration
    name: configuration
media_folder: src/_assets/images
public_folder: /assets
publish_mode: editorial_workflow
site_url: "https://dev.sylvainmetayer.fr"
