name: Daily Build - Triggers Netlify

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: curl
        uses: wei/curl@v1
        with:
          args: -X POST ${{ secrets.netlify_webhook }}
