name: Daily Build - Triggers Netlify

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: curl
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.netlify_webhook }}
          method: "POST"
