name: Eleventy Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Retrieve npm cache (if any)
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-packages

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install packages
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Validate output HTML
        run: npm run test:html
